# $Id$

include ../../config.mk
-include ../../config-local.mk

HELPDIR = $(DOCDIR)/help
DOCFILES = *.webdoc 

all:
	@echo "Done."

test:
	@echo "Nothing to test."

install:
	$(INSTALL) -m 664 $(DOCFILES) $(HELPDIR)

clean:
	@rm -f *.orig *~

# end of file
